import { Platform, StyleSheet } from "react-native";
import { ZORRRO_COLORS, ZORRRO_FONTS } from "$/styles";
import { getHeight } from "$/components/helper";

export const ChatsLandingStyles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: ZORRRO_COLORS.WHITE,
    },
    container: {
        flex: 1,
        backgroundColor: ZORRRO_COLORS.WHITE,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 10,
        paddingBottom: 12,
    },
    headerTitle: {
        fontSize: 24,
        fontFamily: ZORRRO_FONTS?.[700]?.normal,
        color: '#0088C6',
        marginLeft: 12,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#EFF2F5',
        marginHorizontal: 20,
        borderRadius: 240,
        paddingHorizontal: 15,
        height: getHeight(44),
        marginBottom: 16,
    },
    searchIcon: {
        marginRight: 10,
        opacity: 0.5,
        color: '#6F7D90'
    },
    searchInput: {
        flex: 1,
        fontSize: 16,
        color: '#1F2937',
    },
    filtersContainer: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        marginBottom: 20,
    },
    filterChip: {
        flexDirection: 'row',
        paddingHorizontal: 16,
        height: 32,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        marginRight: 10,
    },
    filterChipActive: {
        borderColor: '#085F87',
        backgroundColor: '#E2F6FF',
    },
    filterText: {
        fontSize: 14,
        color: '#6F7D90',
        fontFamily: ZORRRO_FONTS?.[500]?.normal,
    },
    filterTextActive: {
        color: '#085F87',
    },
    filterBadge: {
        backgroundColor: '#0084C8',
        width: 20,
        height: 20,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 6,
    },
    filterBadgeText: {
        color: ZORRRO_COLORS.WHITE,
        fontSize: 10,
        fontFamily: ZORRRO_FONTS?.[700]?.normal,
    },
    listContainer: {
        paddingBottom: 20,
    },
    chatItem: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        paddingVertical: 12,
        alignItems: 'flex-start',
    },
    avatarContainer: {
        width: getHeight(40),
        height: getHeight(40),
        borderRadius: 200,
        backgroundColor: '#085F871A',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    avatarText: {
        color: '#085F87',
        fontSize: 12,
        fontFamily: ZORRRO_FONTS?.[700]?.normal,
    },
    chatDetails: {
        flex: 1,
        justifyContent: 'center',
    },
    chatHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 2,
    },
    chatName: {
        fontSize: 14,
        fontFamily: ZORRRO_FONTS?.[600]?.normal,
        color: '#171D26',
    },
    chatTime: {
        fontSize: 11,
        color: '#6F7D90',
        fontFamily: ZORRRO_FONTS?.[500]?.normal,
    },
    roleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 4,
    },
    roleBadge: {
        borderWidth: 1,
        borderColor: '#DAE0E7',
        borderRadius: 100,
        paddingHorizontal: 6,
        height: getHeight(20),
        justifyContent: 'center',
        alignItems: 'center',
    },
    roleText: {
        fontSize: 10,
        color: '#171D26',
        fontFamily: ZORRRO_FONTS?.[700]?.normal,
    },
    departmentText: {
        fontSize: 11,
        color: '#6F7D90',
        fontFamily: ZORRRO_FONTS?.[500]?.normal,
    },
    messageRow: {
        flexDirection: 'row',
        alignItems: 'center',
        position: 'relative',
        paddingRight: 30,
    },
    checkmarks: {
        marginRight: 4,
    },
    lastMessage: {
        fontSize: 12,
        color: '#6F7D90',
        flex: 1,
        fontFamily: ZORRRO_FONTS?.[500]?.normal,
    },
    unreadBadgeContainer: {
        position: 'absolute',
        right: 0,
        top: 0,
        bottom: 0,
        justifyContent: 'center',
    },
    unreadBadge: {
        backgroundColor: '#0088C6',
        width: 20,
        height: 20,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    unreadBadgeText: {
        color: ZORRRO_COLORS.WHITE,
        fontSize: 10,
        fontFamily: ZORRRO_FONTS?.[700]?.normal,
    },
    fabButton: {
        position: 'absolute',
        bottom: 24,
        right: 24,
        width: 72,
        height: 72,
        borderRadius: 36,
        justifyContent: 'center',
        alignItems: 'center',
    },
    fabGlowOuter: {
        position: 'absolute',
        width: 94,
        height: 94,
        borderRadius: 200,
        backgroundColor: 'rgba(255, 0, 0, 0.17)',
    },
    fabGlowInner: {
        position: 'absolute',
        width: 72,
        height: 72,
        borderRadius: 40,
        backgroundColor: 'rgba(255, 0, 0, 0.16)',
        ...Platform?.OS === 'ios' ? {
            shadowColor: 'rgba(255, 0, 0, 0.25)',
            shadowOffset: { width: 0, height: 0 },
            shadowOpacity: 0.25,
            shadowRadius: 7,
        } : {
            shadowColor: 'rgba(255, 0, 0, 0.25)',
            shadowOffset: { width: 0, height: 0 },
            shadowOpacity: 0.25,
            shadowRadius: 7,
            elevation: 9,
        }
    },
    fabGradient: {
        width: '100%',
        height: '100%',
        borderRadius: 40,
        justifyContent: 'center',
        alignItems: 'center',
    },
    fabText: {
        fontSize: 20,
        fontFamily: ZORRRO_FONTS?.[800]?.normal,
        color: ZORRRO_COLORS.WHITE,
    },
    overlayContainer: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.8)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 30,
    },
    rippleContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 50,
        height: 160,
    },
    ripple: {
        position: 'absolute',
        width: 130,
        height: 130,
        borderRadius: 65,
        backgroundColor: '#DC2626',
    },
    overlaySosButton: {
        width: 130,
        height: 130,
        borderRadius: 65,
        backgroundColor: '#DC2626',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
        shadowColor: '#DC2626',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 1,
        shadowRadius: 20,
        elevation: 10,
    },
    overlaySosText: {
        fontSize: 32,
        fontFamily: ZORRRO_FONTS?.[700]?.normal,
        color: ZORRRO_COLORS.WHITE,
    },
    overlayTitle: {
        fontSize: 22,
        fontFamily: ZORRRO_FONTS?.[700]?.normal,
        color: ZORRRO_COLORS.WHITE,
        marginBottom: 10,
        textAlign: 'center',
    },
    overlaySubtitle: {
        fontSize: 14,
        color: '#D1D5DB',
        textAlign: 'center',
        lineHeight: 22,
        marginBottom: 40,
    },
    cancelButton: {
        paddingVertical: 10,
        paddingHorizontal: 30,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: ZORRRO_COLORS.WHITE,
        backgroundColor: 'transparent',
    },
    cancelButtonText: {
        color: ZORRRO_COLORS.WHITE,
        fontSize: 16,
    },
    confirmOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.35)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    confirmCard: {
        width: '100%',
        backgroundColor: ZORRRO_COLORS.WHITE,
        borderRadius: 20,
        paddingVertical: 20,
        paddingHorizontal: 18,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.18,
        shadowRadius: 22,
        elevation: 10,
    },
    confirmTitle: {
        fontSize: 20,
        color: '#171D26',
        fontFamily: ZORRRO_FONTS?.[700]?.normal,
        marginBottom: 8,
    },
    confirmSubtitle: {
        fontSize: 14,
        lineHeight: 20,
        color: '#5B6676',
        fontFamily: ZORRRO_FONTS?.[500]?.normal,
        marginBottom: 18,
    },
    confirmActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
    },
    confirmCancelButton: {
        paddingVertical: 10,
        paddingHorizontal: 14,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#DAE0E7',
        marginRight: 10,
    },
    confirmCancelText: {
        color: '#6F7D90',
        fontSize: 14,
        fontFamily: ZORRRO_FONTS?.[600]?.normal,
    },
    confirmSendButton: {
        paddingVertical: 10,
        paddingHorizontal: 14,
        borderRadius: 10,
        backgroundColor: '#D62800',
    },
    confirmSendText: {
        color: ZORRRO_COLORS.WHITE,
        fontSize: 14,
        fontFamily: ZORRRO_FONTS?.[700]?.normal,
    },
});