import { Platform, StyleSheet } from "react-native";
import { ZORRRO_COLORS, ZORRRO_FONTS } from "$/styles";

export const ChatDetailsStyles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: ZORRRO_COLORS?.WHITE,
    },
    keyboardWrap: {
        flex: 1,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    backButton: {
        padding: 4,
        marginRight: 8,
    },
    headerProfile: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
    },
    avatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#E0F2FE',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    avatarText: {
        color: '#0284C7',
        fontSize: 16,
        fontFamily: ZORRRO_FONTS?.[700]?.normal,
    },
    headerInfo: {
        justifyContent: 'center',
    },
    headerName: {
        fontSize: 16,
        fontFamily: ZORRRO_FONTS?.[600]?.normal,
        color: '#111827',
    },
    headerSubtitle: {
        fontSize: 12,
        color: '#6B7280',
    },
    moreButton: {
        padding: 8,
    },
    moreIcon: {
        fontSize: 24,
        color: '#111827',
        fontFamily: ZORRRO_FONTS?.[800]?.normal,
    },
    chatList: {
        padding: 16,
    },
    messageBubble: {
        maxWidth: '80%',
        padding: 12,
        borderRadius: 16,
        marginBottom: 16,
    },
    sentBubble: {
        alignSelf: 'flex-end',
        backgroundColor: '#0084C8',
        borderBottomRightRadius: 4,
    },
    receivedBubble: {
        alignSelf: 'flex-start',
        backgroundColor: '#F3F4F6',
        borderBottomLeftRadius: 4,
    },
    messageText: {
        fontSize: 15,
        lineHeight: 22,
    },
    sentText: {
        color: ZORRRO_COLORS?.WHITE,
    },
    receivedText: {
        color: '#1F2937',
    },
    timeContainer: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        marginTop: 4,
    },
    timeText: {
        fontSize: 11,
    },
    sentTimeText: {
        color: 'rgba(255,255,255,0.7)',
    },
    receivedTimeText: {
        color: '#9CA3AF',
    },
    checkmark: {
        marginLeft: 4,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderTopWidth: 1,
        borderTopColor: '#00151F1F',
        backgroundColor: ZORRRO_COLORS?.WHITE,
        ...(Platform?.OS === 'android'
            ? {
                elevation: 2,
                shadowColor: '#0000001F',
                shadowOffset: { width: 0, height: 2 },
                shadowOpacity: 0.12,
                shadowRadius: 6,
            }
            : {
                shadowColor: '#0000001F',
                shadowOffset: { width: 0, height: 2 },
                shadowOpacity: 0.12,
                shadowRadius: 6,
            }),

    },
    leftActionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingLeft: 6,
        marginRight: 10,
    },
    textInputWrapper: {
        flex: 1,
        backgroundColor: '#EFF2F5',
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 9,
        marginRight: 10,
        minHeight: 48,
        justifyContent: 'center',
    },
    textInput: {
        fontSize: 16,
        color: '#1F2937',
        padding: 0,
        maxHeight: 100,
    },
    sendButton: {
        width: 48,
        height: 48,
        borderRadius: 10,
        backgroundColor: '#0088C6',
        justifyContent: 'center',
        alignItems: 'center',
    },
    recordingPanel: {
        borderTopWidth: 1,
        borderTopColor: '#00151F1F',
        backgroundColor: ZORRRO_COLORS?.WHITE,
        paddingHorizontal: 14,
        paddingTop: 10,
        paddingBottom: 8,
    },
    recordingTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    recordingLiveDot: {
        color: '#E11D48',
        fontSize: 14,
        marginRight: 8,
    },
    recordingWaveformRow: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
    },
    recordingWaveBar: {
        width: 2,
        borderRadius: 2,
        backgroundColor: '#D1D5DB',
        marginRight: 2,
    },
    recordingDurationText: {
        fontSize: 24,
        color: '#111827',
        marginLeft: 8,
    },
    recordingBottomRow: {
        marginTop: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 4,
    },
    recordingBottomIcon: {
        fontSize: 20,
        color: '#6B7280',
    },
    recordingMicHint: {
        fontSize: 24,
        color: '#E11D48',
    },
    recordingSendButton: {
        width: 36,
        height: 36,
        borderRadius: 6,
        backgroundColor: '#0088C6',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'transparent',
    },
    menuContainer: {
        position: 'absolute',
        top: 60,
        right: 16,
        backgroundColor: ZORRRO_COLORS?.WHITE,
        borderRadius: 12,
        paddingVertical: 8,
        width: 200,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 8,
    },
    menuItem: {
        paddingVertical: 12,
        paddingHorizontal: 16,
    },
    menuText: {
        fontSize: 15,
        color: '#1F2937',
    },
    centerModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    muteModalContainer: {
        backgroundColor: ZORRRO_COLORS?.WHITE,
        borderRadius: 16,
        width: '80%',
        padding: 24,
    },
    muteModalTitle: {
        fontSize: 18,
        fontFamily: ZORRRO_FONTS?.[700]?.normal,
        color: '#111827',
        marginBottom: 8,
    },
    muteModalSubtitle: {
        fontSize: 14,
        color: '#6B7280',
        marginBottom: 20,
        lineHeight: 20,
    },
    radioRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
    },
    radioCircle: {
        height: 20,
        width: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#9CA3AF',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    radioCircleSelected: {
        borderColor: '#0084C8',
    },
    radioDot: {
        height: 10,
        width: 10,
        borderRadius: 5,
        backgroundColor: '#0084C8',
    },
    radioText: {
        fontSize: 15,
        color: '#111827',
    },
    muteActionRow: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginTop: 24,
    },
    muteActionBtn: {
        marginLeft: 24,
    },
    muteActionText: {
        color: '#0084C8',
        fontSize: 15,
        fontFamily: ZORRRO_FONTS?.[600]?.normal,
    },
    bottomModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'flex-end',
    },
    attachmentContainer: {
        backgroundColor: ZORRRO_COLORS?.WHITE,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        paddingBottom: 40,
    },
    attachmentRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    attachmentItem: {
        alignItems: 'center',
    },
    attachmentIconBox: {
        width: 60,
        height: 60,
        borderRadius: 20,
        backgroundColor: ZORRRO_COLORS?.WHITE,
        borderWidth: 1,
        borderColor: '#F3F4F6',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    attachmentText: {
        fontSize: 13,
        color: '#4B5563',
        fontFamily: ZORRRO_FONTS?.[500]?.normal,
    },
    recentMediaTitle: {
        marginTop: 18,
        marginBottom: 8,
        fontSize: 13,
        fontFamily: ZORRRO_FONTS?.[600]?.normal,
        color: '#374151',
    },
    recentMediaHint: {
        fontSize: 13,
        color: '#9CA3AF',
        marginBottom: 4,
    },
    recentMediaList: {
        paddingVertical: 4,
    },
    recentMediaThumbWrapper: {
        marginRight: 10,
        borderRadius: 10,
        overflow: 'hidden',
    },
    recentMediaThumb: {
        width: 68,
        height: 68,
        borderRadius: 10,
        backgroundColor: '#E5E7EB',
    },
    cameraTile: {
        width: 68,
        height: 68,
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        justifyContent: 'center',
        alignItems: 'center',
    },
    cameraTileText: {
        marginTop: 4,
        fontSize: 10,
        color: '#6B7280',
        fontWeight: '600',
    },
    recentMediaSelectedOverlay: {
        position: 'absolute',
        top: 4,
        right: 4,
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: '#0084C8',
        justifyContent: 'center',
        alignItems: 'center',
    },
    recentMediaSelectedText: {
        color: ZORRRO_COLORS?.WHITE,
        fontSize: 12,
        fontFamily: ZORRRO_FONTS?.[700]?.normal,
    },
    sendSelectedButton: {
        marginTop: 12,
        backgroundColor: '#0084C8',
        borderRadius: 10,
        paddingVertical: 10,
        alignItems: 'center',
    },
    sendSelectedText: {
        color: ZORRRO_COLORS?.WHITE,
        fontFamily: ZORRRO_FONTS?.[600]?.normal,
    },
    messageSelected: {
        opacity: 0.7,
        borderWidth: 2,
        borderColor: '#0084C8',
    },
    actionModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    actionMenuContainer: {
        width: 250,
        backgroundColor: ZORRRO_COLORS?.WHITE,
        borderRadius: 16,
        paddingVertical: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.15,
        shadowRadius: 20,
        elevation: 10,
    },
    actionMenuItem: {
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    actionMenuText: {
        fontSize: 16,
        color: '#1F2937',
        fontFamily: ZORRRO_FONTS?.[500]?.normal,
    },
    typingIndicatorContainer: {
        alignSelf: 'flex-start',
        backgroundColor: '#F3F4F6',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 16,
        borderBottomLeftRadius: 4,
        marginBottom: 10,
    },
    typingText: {
        color: '#6B7280',
        fontSize: 14,
        fontStyle: 'italic',
    },
    messageImage: {
        width: 200,
        height: 200,
        borderRadius: 8,
        marginBottom: 4,
    },
    docMessageContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: 200,
        marginBottom: 4,
    },
    docIconBox: {
        width: 40,
        height: 40,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    docInfo: {
        flex: 1,
    },
    docName: {
        fontSize: 14,
        fontFamily: ZORRRO_FONTS?.[500]?.normal,
        marginBottom: 2,
    },
    docSize: {
        fontSize: 11,
    },
    audioContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: 200,
        marginBottom: 4,
    },
    audioWaveMock: {
        flex: 1,
        height: 4,
        borderRadius: 2,
        marginHorizontal: 12,
        overflow: 'hidden',
    },
    audioWaveProgress: {
        height: '100%',
        backgroundColor: ZORRRO_COLORS?.WHITE,
    },
    audioTime: {
        fontSize: 12,
        fontFamily: ZORRRO_FONTS?.[500]?.normal,
    },
    recordingWrapper: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
    },
    recordingDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: '#DC2626',
        marginRight: 10,
    },
    recordingTimer: {
        fontSize: 16,
        color: '#1F2937',
        fontFamily: ZORRRO_FONTS?.[500]?.normal,
        width: 45,
    },
    recordingSlideText: {
        fontSize: 14,
        color: '#9CA3AF',
        fontStyle: 'italic',
        marginLeft: 'auto',
    },
    previewContainer: {
        backgroundColor: ZORRRO_COLORS?.WHITE,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 20,
        paddingBottom: 32,
    },
    previewTitle: {
        fontSize: 16,
        fontFamily: ZORRRO_FONTS?.[600]?.normal,
        color: '#111827',
        marginBottom: 12,
    },
    previewImage: {
        width: '100%',
        height: 280,
        borderRadius: 12,
        marginBottom: 16,
    },
    previewDocContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 10,
        marginBottom: 16,
    },
    previewDocMeta: {
        marginLeft: 12,
        flex: 1,
    },
    previewDocName: {
        fontSize: 15,
        color: '#111827',
        fontFamily: ZORRRO_FONTS?.[500]?.normal,
    },
    previewDocSize: {
        marginTop: 4,
        fontSize: 12,
        color: '#6B7280',
    },
    previewAudioContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F3F4F6',
        borderRadius: 12,
        padding: 12,
        marginBottom: 16,
    },
    previewAudioMeta: {
        flex: 1,
        marginLeft: 10,
        marginRight: 10,
    },
    previewAudioText: {
        fontSize: 14,
        color: '#111827',
        marginBottom: 6,
    },
    previewAudioWaveBase: {
        width: '100%',
        height: 4,
        backgroundColor: '#D1D5DB',
        borderRadius: 2,
        overflow: 'hidden',
    },
    previewAudioWaveProgress: {
        height: 4,
        borderRadius: 2,
        backgroundColor: '#0EA5E9',
    },
    previewAudioDuration: {
        fontSize: 13,
        color: '#6B7280',
    },
    previewActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
    },
    previewCancelButton: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 8,
        backgroundColor: '#F3F4F6',
        marginRight: 10,
    },
    previewCancelText: {
        color: '#4B5563',
        fontFamily: ZORRRO_FONTS?.[500]?.normal,
    },
    previewSendButton: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 8,
        backgroundColor: '#0084C8',
    },
    previewSendText: {
        color: ZORRRO_COLORS?.WHITE,
        fontFamily: ZORRRO_FONTS?.[600]?.normal,
    },
});